site_title: Japanese Course of Study LOD
base_uri: https://w3id.org/jp-cos/
uri_mappings:
  - regexp: !ruby/regexp /^(\d\w\w)(\w{13})$/
    path: '\1/\2'
locale: en
title_property_perclass:
  https://w3id.org/jp-cos/Item: http://schema.org/description
breadcrumbs:
  - property: http://schema.org/hasPart
    inverse: true
    label: https://w3id.org/jp-cos/sectionNumber
  - property: https://w3id.org/jp-cos/courseOfStudy
top_class: https://w3id.org/jp-cos/CourseOfStudy
admin_name: Education Data Plus Research group
copyright_year: 2021-2023
css_file: ../style.css
javascript_file: custom.js
logo: https://w3id.org/jp-cos/logo.png
google_analytics: G-ZW2V5CQLY9
google_custom_search_id: 75eea1908d53d46ba
additional_link:
  - label: 日本語
    href: https://w3id.org/jp-cos/
output_turtle: false
shape_orders:
  - https://w3id.org/jp-cos/ItemShape
  - https://w3id.org/jp-cos/DatasetShape
  - https://w3id.org/jp-cos/CourseOfStudyShape
  - https://w3id.org/jp-cos/CourseOfStudyRevisionShape
about_toc: true
