site_title: 学習指導要領LOD
base_uri: https://w3id.org/jp-cos/
uri_mappings:
  - regexp: !ruby/regexp /^(\d\w\w)(\w{13})$/
    path: '\1/\2'
locale: ja
title_property_perclass:
  https://w3id.org/jp-cos/Item: http://schema.org/description
breadcrumbs:
  - property: http://schema.org/hasPart
    inverse: true
    label: https://w3id.org/jp-cos/sectionNumber
  - property: https://w3id.org/jp-cos/courseOfStudy
top_class: https://w3id.org/jp-cos/CourseOfStudy
admin_name: 教育データプラス研究会
copyright_year: 2021
